### ISSUE TITLE
Bot won't understand confirmation code

### ISSUE THREAD

**Issue by CruiseMan** [system76/help_desk#12]
I did not want to bother support team, but after order placed email with example of verification code is suggested as:
<img width="389" alt="Screen Shot 2021-03-27 at 4 17 27 PM" src="https://user-images.githubusercontent.com/15807643/112737447-ed1c3280-8f17-11eb-890e-a308c2df3976.png">
In reality my bank displays like so:
![IMG_2483](https://user-images.githubusercontent.com/15807643/112737469-1046e200-8f18-11eb-9e32-d86d629908f6.jpg)
I tried to sent code like `F2 Ks7` and `F2Ks7` and `F2KS7` non of them worked.

**Comment by CruiseMan** [comment]
@btkostner can you help ?

**Comment by btkostner** [comment]
I'm sorry, but due to security reasons I can't help with purchases or support here. You can respond to the ticket via email and it will show up in our support queue for a human to help you through it. I can tell you however that we don't use a bot to check those codes and each verification gets checked by a human on our support team.

**Comment by CruiseMan** [comment]
> I'm sorry, but due to security reasons I can't help with purchases or support here. You can respond to the ticket via email and it will show up in our support queue for a human to help you through it. I can tell you however that we don't use a bot to check those codes and each verification gets checked by a human on our support team.

Doesn't make sense what you saying, when purchased made email to confirm sent, once I replied with the code automatic email send back that code wasn't recognized, so not human involved in this. Why purchasing laptop takes manual approve, doesn't make sense to me in 2021.

**Comment by doomspork** [comment]
Howdy @CruiseMan, if you could reach out to us via help@system76.com we'll be able to get you taken care of. Thanks so much for your understanding! :grinning:

**Comment by CruiseMan** [comment]
> Howdy @CruiseMan, if you could reach out to us via [help@system76.com](mailto:help@system76.com) we'll be able to get you taken care of. Thanks so much for your understanding! 😀

Thank you. But I would like to see no human involvement in purchase confirmation. But what I was hoping to hear from you(System76) is that you will fix issue with confirmation code, that all. I thought this is the best place you report about it.
